.TH cw1-6005-ac23g08 1 "22 February 2012" "v1.2"
.SH NAME cw1-6005-ac23g08 \- RSS Feed Reader
.SH SYNOPSIS
.B cw1-6005-ac23g08
.I [OPTION]
.SH DESCRIPTION
The RSS Feed Reader will read a specified RSS Feed and display its items.

If no feed is specified then a configuration containing preset RSS Feeds are used instead.
.SH OPTIONS
--feeds feed1 [,feed2,..]
feed option and the RSS feeds specified

--items n
the number of items to show from each feed
.SH AUTHOR
Adam Costello <ac23g08@ecs.soton.ac.uk>
